# Generated by Django 5.1.7 on 2025-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_information_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
