# Generated by Django 5.1.7 on 2025-04-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_information_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='details',
        ),
    ]
