# Generated by Django 5.1.7 on 2025-04-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together=set(),
        ),
    ]
