# Generated by Django 5.1.7 on 2025-04-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productlike_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlike',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='productlike',
            old_name='created_at',
            new_name='created',
        ),
    ]
