# Generated by Django 5.1.7 on 2025-04-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlike',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
