# Generated by Django 5.1.7 on 2025-04-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productlike_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='slug',
        ),
    ]
