# Generated by Django 5.1.7 on 2025-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_discountcode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
