# Generated by Django 5.1.7 on 2025-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_discountcode_expires_at_discountcode_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
